### ISSUE TITLE
USBデバイスの指定ができない

### ISSUE THREAD

**Issue by uhobeike** [AtsushiSaito/rt_usb_9axis_sensor#5]
READMEにUSBデバイスの指定ができるように書かれているが、現在のlaunchファイルだと設定できないと思われる。
![README Options](https://i.gyazo.com/2ccb9fa4265af388a225b7ca502c07f2.png "README Options")
___
こちらは、実際に動かしたときの動画です。
* 最初はコード修正後の挙動、次にコード修正前に戻したときの挙動、最後に最初の時と同じようにコードを修正したときの挙動です。

|実際に動かした[動画]|
|---|
|[![](https://i.gyazo.com/3d2c5fb806a6f65155c92eb380e2618e.png)](https://youtu.be/86OdAvtGt_0)|

動かしているときの状況としては、HOKUYOのUSB_URGが`/dev/ttyACM0`でRTのUSB出力9軸IMUセンサモジュールが`/dev/ttyACM1`でした。

ということで、AtsushiSaito/rt_usb_9axis_sensorのパッケージでIMUを使用するには、`/dev/ttyACM1`を指定する必要があったので、`roslaunch rt_usb_9axis_sensor rt_usb_9axis_sensor.launch port:="/dev/ttyACM1"`を実行したのですが、上手く指定することが出来ませんでした。

なので、上手く指定できるようにコードを修正しました。#4

|`roslaunch rt_usb_9axis_sensor rt_usb_9axis_sensor.launch port:="/dev/ttyACM1"`失敗(コード修正前)|
|---|
|<img width="500" src="https://i.gyazo.com/7d493cbe41de63d876b7a649c6bf3dbb.png">|

|`roslaunch rt_usb_9axis_sensor rt_usb_9axis_sensor.launch port:="/dev/ttyACM1"`成功(コード修正後)|
|---|
|<img width="500" src="https://i.gyazo.com/5ebfcb859eca60f7692186f153353b69.jpg">|

**Comment by AtsushiSaito** [comment]
@uhobeike ありがとうございます。
関連のPRがマージされたため、このissueを閉じます。
